name: Debian

on:
  push:
    paths:
      - .github/workflows/debian.yml
      - assets

env:
  CONAN_URL: ${{ secrets.CONAN_URL }}
  CONAN_LOGIN_USERNAME_XRPLF: ${{ secrets.CONAN_USERNAME }}
  CONAN_PASSWORD_XRPLF: ${{ secrets.CONAN_PASSWORD }}

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
        docker:
          - image: ghcr.io/xrplf/ci/debian-bookworm:gcc-12
          - image: ghcr.io/xrplf/ci/debian-bookworm:gcc-13
          - image: ghcr.io/xrplf/ci/debian-bookworm:gcc-14
          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-16
          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-17
          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-18
          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-19
          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-20
        package:
          - name: snappy
            version: 1.10.0
    runs-on: ${{ matrix.architecture.runner }}
    container: ${{ matrix.docker.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build the recipe
        working-directory: recipes
        run: conan create ${{ matrix.package.name }} --version ${{ matrix.package.version }} --build=missing --update
      - name: Upload the recipe
        run: conan upload '${{ matrix.package.name }}' --remote ${{ env.CONAN_URL }} --confirm --dry-run
