name: Debian

on:
  push:
    paths:
      - .github/workflows/debian.yml
      - recipes

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CONAN_URL: ${{ secrets.CONAN_URL }}
  CONAN_LOGIN_USERNAME_XRPLF: ${{ secrets.CONAN_USERNAME }}
  CONAN_PASSWORD_XRPLF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_GLOBAL_CONF: |
    core.download:parallel={{ os.cpu_count() }}
    core.upload:parallel={{ os.cpu_count() }}
    core:default_build_profile=libxrpl
    core:default_profile=libxrpl
    tools.build:jobs={{ (os.cpu_count() * 4/5) | int }}
    tools.build:verbosity=verbose
    tools.compilation:verbosity=verbose

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - runner: ubuntu-24.04
#          - runner: ubuntu-24.04-arm
        docker:
          - image: ghcr.io/xrplf/ci/debian-bookworm:gcc-12
#          - image: ghcr.io/xrplf/ci/debian-bookworm:gcc-13
#          - image: ghcr.io/xrplf/ci/debian-bookworm:gcc-14
#          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-16
#          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-17
#          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-18
#          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-19
#          - image: ghcr.io/xrplf/ci/debian-bookworm:clang-20
        build:
          - type: Debug
#          - type: Release
        package:
          - name: snappy
            version: 1.1.10
    runs-on: ${{ matrix.architecture.runner }}
    container: ${{ matrix.docker.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Conan
        run: |
          echo "${CONAN_GLOBAL_CONF}" >> $(conan config home)/global.conf
          conan config install profiles/ -tf $(conan config home)/profiles/
          conan profile show
      - name: Build the recipe
        working-directory: recipes/${{ matrix.package.name }}/all
        run: |
          conan create .  \
                --version ${{ matrix.package.version }} \
                --build=missing \
                --settings=build_type=${{ matrix.build.type }} \
                --update
      - name: Upload the recipe
        run: |
          conan upload '${{ matrix.package.name }}' \
                --remote ${{ env.CONAN_URL }} \
                --confirm \
                --dry-run
