name: Export

on:
  pull_request:
    paths:
      - ".github/workflows/export.yml"
      - ".github/workflows/export-one-remote.yml"
      - "recipes/**"
      - "export_all.sh"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/export.yml"
      - ".github/workflows/export-one-remote.yml"
      - "recipes/**"
      - "export_all.sh"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CONAN_REMOTE_NAME: xrplf

jobs:
  export-new:
    uses: ./.github/workflows/export-one-remote.yml
    with:
      CONAN_REMOTE_URL: https://conan.xrplf.org/repository/conan/
    secrets:
      CONAN_LOGIN_USERNAME_XRPLF: ${{ secrets.NEXUS_REMOTE_USERNAME }}
      CONAN_PASSWORD_XRPLF: ${{ secrets.NEXUS_REMOTE_PASSWORD }}

  export-old:
    uses: ./.github/workflows/export-one-remote.yml
    with:
      CONAN_REMOTE_URL: https://conan.ripplex.io
    secrets:
      CONAN_LOGIN_USERNAME_XRPLF: ${{ secrets.CONAN_REMOTE_USERNAME }}
      CONAN_PASSWORD_XRPLF: ${{ secrets.CONAN_REMOTE_PASSWORD }}
